import ContentSection from "./ContentSection";
import HeaderSection from "./HeaderSection";
import styles from "./page.module.scss";

export default function AuditLogPage() {
  return (
    <main className={styles.auditLogPageContainer}>
      <HeaderSection />
      <ContentSection auditData={FAKE_AUDIT_DATA} />
    </main>
  )
}

const FAKE_AUDIT_DATA = [
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
  {
    timestamp: "23/05/2023  3:35:00 PM",
    performedBy: "Sarah Tay (100001a)",
    userRole: "RM Approver",
    applicationId: "10000027",
    activity: "Send the application to NR for screening",
    reason: "Wrong Customer Contact Number, please resubmit",
    fromStatus: "Pending RM Approver",
    toStatus: "Pending for Review in Net Reveal",
  },
]
